worker_first:
    build: .
    volumes:
      - .:/code
    dockerfile: Dockerfile_worker
    command: First

worker_second:
    build: .
    volumes:
      - .:/code
    dockerfile: Dockerfile_worker
    command: Second

gateway:
    build: .
    volumes:
      - .:/code
    dockerfile: Dockerfile_gateway
    links:
     - worker_first:first
     - worker_second:second
    ports:
     - "2345:2345"
