version: '2'

services:

  gateway:
    build:
      context: .
      dockerfile: Dockerfile_gateway
    volumes:
      - .:/code
    links:
     - worker_first:first
     - worker_second:second
    ports:
     - "2345:2345"

  worker_first:
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - .:/code
    command: First

  worker_second:
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - .:/code
    command: Second
